### ISSUE TITLE
service hash changes for every deploy (when fetching from git)

### ISSUE THREAD

**Issue by ilgooz** [mesg-foundation/core#379]
Service hash should not change if there is no change on Service type. Docker image sha256 value is a part of Service type.  On my machine _container.Build()_ produces different hashes even if there is no change on the source code but when I run plain _docker build_ on service folder I get the same sha256 every time. This change on sha256 value makes service hash change for every deploy.

core version: [dev](https://github.com/mesg-foundation/core/commit/08f072adf6b3339b7bfd47289d7409565c9317da) and [an older](https://github.com/mesg-foundation/core/commit/bd84ad1d54eadfb8aa2bd79ac0c7c68f775f9c03) version right before refactoring container package.
docker: Version 18.06.0-ce-mac70 (26399)

**Comment by antho1404** [comment]
Can you share the service you are running because I cannot reproduce with my test services. I ran with the latest `mesg-core v1.2.0` and the actual version on the dev branch and both are working fine for me

Docker version is the same I guess

Docker version 18.06.0-ce, build 0ffa825

**Comment by ilgooz** [comment]
`$ ./dev-core`
`$ go run ./cli/main.go service deploy https://github.com/mesg-foundation/service-webhook`

core logs: 
```
Ilkers-MacBook-Pro:core ilgooz$ ./dev-core 
Building mesg/core:local...
Sending build context to Docker daemon  24.31MB
Step 1/9 : FROM golang:1.10.3-stretch AS build
 ---> d0e7a411e3da
Step 2/9 : WORKDIR src/github.com/mesg-foundation/core
 ---> Using cache
 ---> 74e72b900665
Step 3/9 : COPY . .
 ---> Using cache
 ---> 95c4b4b00f22
Step 4/9 : ARG version
 ---> Using cache
 ---> dc850601104a
Step 5/9 : RUN go build -o mesg-core       -ldflags="-X 'github.com/mesg-foundation/core/version.Version=$version'"       core/main.go
 ---> Using cache
 ---> bbd0804f80a4
Step 6/9 : FROM ubuntu:18.04
 ---> 735f80812f90
Step 7/9 : WORKDIR /app
 ---> Using cache
 ---> ae73005a8e2b
Step 8/9 : COPY --from=build /go/src/github.com/mesg-foundation/core/mesg-core .
 ---> Using cache
 ---> c1e308ec663b
Step 9/9 : CMD ["./mesg-core"]
 ---> Using cache
 ---> 8d6fff15db97
Successfully built 8d6fff15db97
Successfully tagged mesg/core:local
MESG Core stoppedore... 
MESG Core is running... 
time="2018-08-22T09:25:24Z" level=info msg="Starting MESG Core local"
time="2018-08-22T09:25:24Z" level=info msg="Server listens on [::]:50052"
time="2018-08-22T09:25:24Z" level=info msg="Server listens on /mesg/server.sock"
time="2018-08-22T09:25:38Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=DeployService grpc.service=api.Core grpc.start_time="2018-08-22T09:25:38Z" grpc.time_ms=73.22 span.kind=server system=grpc
time="2018-08-22T09:26:07Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=DeployService grpc.service=api.Core grpc.start_time="2018-08-22T09:26:07Z" grpc.time_ms=69.028 span.kind=server system=grpc
```

cli logs: 
```
Ilkers-MacBook-Pro:core ilgooz$ go run ./cli/main.go service deploy https://github.com/mesg-foundation/service-webhook
✔ Service downloaded with success
✔ Image built with success
Service deployed with ID: v1_958e63c599fefeb3c00744395e24c538
To start it, run the command: mesg-core service start v1_958e63c599fefeb3c00744395e24c538
Ilkers-MacBook-Pro:core ilgooz$ go run ./cli/main.go service deploy https://github.com/mesg-foundation/service-webhook
✔ Service downloaded with success
✔ Image built with success
Service deployed with ID: v1_c432377810d44d6150da976f08e652c2
To start it, run the command: mesg-core service start v1_c432377810d44d6150da976f08e652c2
```

**Comment by ilgooz** [comment]
the previous Docker version that I provided was retrieved from https://store.docker.com/editions/community/docker-ce-desktop-mac app

here is the Docker version from Terminal
```
$ docker -v
Docker version 18.06.0-ce, build 0ffa825
```

**Comment by antho1404** [comment]
Ok in this case I can reproduce but it's normal that the hash changes because in this case the service will be downloaded in a temp folder with a "random" name and the every files will have a different path and I guess docker take this into account to calculate the hash of its image but if you fetch the service and deploy this one multiple time the exact same hash will be created. This is really related to the fact that we are downloading it

**Comment by ilgooz** [comment]
I understand, but I thought we only send_(container.Build())_ the content of the temp folder with a tarball, not the temp folder itself with its content. Does Docker also take account modification date of files? We might need to check that one too. 

But this is still a bug to me.

**Comment by antho1404** [comment]
For information this is not related of the folder where it is stored so it is probably due to the git clone that change something maybe a file in the `.git` with the last sync date or something like that
Still investigate

**Comment by krhubert** [comment]
@antho1404 This is fixed, right?

I'm closing it because I think it's been fixed already. If I'm wrong just reopen the issue.

**Comment by ilgooz** [comment]
yes we still have this, to reproduce please run following two times:
`./dev-cli service dev https://github.com/mesg-foundation/service-webhook`

**Comment by NicolasMahe** [comment]
Close with https://github.com/mesg-foundation/core/pull/482
